export const CLEAN_TRACKSLIST = 'CLEAN_TRACKSLIST';
export const GET_PLAYLIST_TRACKS = 'GET_PLAYLIST_TRACKS';
export const GET_PLAYLIST_TRACKS_FAIL = 'GET_PLAYLIST_TRACKS_FAIL';
export const GET_PLAYLIST_TRACKS_SUCCESS = 'GET_PLAYLIST_TRACKS_SUCCESS';
export const GET_TRACKSLIST = 'GET_TRACKSLIST';
export const GET_TRACKSLIST_FAIL = 'GET_TRACKSLIST_FAIL';
export const GET_TRACKSLIST_SUCCESS = 'GET_TRACKSLIST_SUCCESS';
