export const GET_RECENTLY_LISTENED = 'GET_RECENTLY_LISTENED';
export const GET_RECENTLY_LISTENED_FAIL = 'GET_RECENTLY_LISTENED_FAIL';
export const GET_RECENTLY_LISTENED_SUCCESS = 'GET_RECENTLY_LISTENED_SUCCESS';
